name: Check Markdown links

on: push
name: Check links for modified files
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tcort/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        folder-path: ''
        file-path: './README.md'
